from backend.infrastructure.reply_detector import classify_reply_type

def test_classify_reply_type_ooo():
    assert classify_reply_type("I am OOO until next week.") == "ooo"
    assert classify_reply_type("Out of office: I am away.") == "ooo"
    assert classify_reply_type("This is an auto-reply generated by...") == "ooo"
    assert classify_reply_type("VACATION RESPONDER: Hello") == "ooo"

def test_classify_reply_type_normal():
    assert classify_reply_type("Hi, thanks for reaching out. Yes, I can do that.") == "normal"
    assert classify_reply_type("I am looking into this.") == "normal"
